baseURL = "https://rainbain.github.io/rainbain-blog/"
languageCode = "en-us"
theme = "PaperMod"

[pagination]
    pagerSize = 10

[params]
    author = "Rainbain Blog"
    description = "Rainbain's Blog"
    defaultTheme = "dark"
    ShowReadingTime = true
    ShowCodeCopyButtons = true
    ShowPostNavLinks = true
    math = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
